# Generated by Django 4.0.5 on 2022-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.IntegerField()),
                ('price_dollar', models.FloatField()),
                ('price_rub', models.FloatField()),
                ('delivery_data', models.DateField()),
            ],
        ),
    ]
